name: reinforcement_learning
channels:
  - defaults
dependencies:
  - ipykernel=5.1.4
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.16.0
  - jinja2=2.11.1
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.1.0
  - jupyter_core=4.6.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - pandas=1.0.1
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - pip=20.0.2
  - python=3.7.6
  - scipy=1.4.1
  - seaborn=0.10.0
  - pip:
    - gym==0.17.1

